# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MichisirubeApplication' do
pod 'Alamofire'
pod 'MaterialComponents/Dialogs'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MichisirubeApplication

end
