name: MichisirubeApplication
options:
  bundleIdPrefix: com.icloud.kaitokudou2468110921
targets:
  MichisirubeApplication:
    type: application
    platform: iOS
    sources: MichisirubeApplication
    settings:
      CURRENT_PROJECT_VERSION: 1